
###
POST http://localhost:5000/api/customers
Content-Type: application/json

{
      
"email": "ALEX@hotmail.co.uk",
"FirstName":"ALEX",
"LastName":"ASH", 
"password": 123  
    }




###
GET http://localhost:5000/api/%123

###

GET http://localhost:5000/hey
